# 参照: https://docs.astral.sh/ruff/configuration/#__tabbed_1_1
[tool.ruff]
# Ruffの実行対象外のディレクトリを指定します。
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "src/user", # 個人ファイル
]

# Blackと同様の設定
line-length = 88
indent-width = 4

# Python 3.8を想定
target-version = "py38"

[tool.ruff.lint]
# 有効なルールの一覧
select = [
    "E4", # [import-order] isortを使用するため除外
    "E7",
    "E9",
    "F",
    "D",
    "Q000", # [bad-quotes-inline-string] ダブルクォートを使用(後述のquote-styleで設定)
]

# 各ルールの除外理由をコメントして残るようにしておくと良いと思います
ignore = [
    "D407", # [dashed-underline-after-section]googleのdocstringを使用するため除外
    "D211", # [no-blank-line-before-class] D203とコンフリクトするため除外
    "D213", # [multi-line-summary-second-line] D212とコンフリクトするため除外
]


# すべての有効なルールに対する修正 (`--fix` 時) を許可
fixable = ["ALL"]
unfixable = []


[tool.ruff.format]
# Blackと同様に文字列にはダブルクォートを使用
quote-style = "double"

# Blackと同様にタブではなくスペースでインデント
indent-style = "space"

# Blackと同様に適切な行の末尾を自動的に検出
line-ending = "auto"